version: '3'
services:
  web:
    build: ./app
    restart: always
    container_name: nr_node
    command: npm start
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      PORT: 9000
    links:
      - "redis:redis"
  redis:
    image: redis:alpine
    restart: always
    container_name: nr_redis
#    ports:
#      - "6379:6379"
    volumes:
      - ./redis-data:/data